require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ourservices", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Ourservice. As you add validations to Ourservice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ourservice.create! valid_attributes
      get ourservices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ourservice = Ourservice.create! valid_attributes
      get ourservice_url(ourservice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ourservice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ourservice = Ourservice.create! valid_attributes
      get edit_ourservice_url(ourservice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ourservice" do
        expect {
          post ourservices_url, params: { ourservice: valid_attributes }
        }.to change(Ourservice, :count).by(1)
      end

      it "redirects to the created ourservice" do
        post ourservices_url, params: { ourservice: valid_attributes }
        expect(response).to redirect_to(ourservice_url(Ourservice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ourservice" do
        expect {
          post ourservices_url, params: { ourservice: invalid_attributes }
        }.to change(Ourservice, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ourservices_url, params: { ourservice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ourservice" do
        ourservice = Ourservice.create! valid_attributes
        patch ourservice_url(ourservice), params: { ourservice: new_attributes }
        ourservice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ourservice" do
        ourservice = Ourservice.create! valid_attributes
        patch ourservice_url(ourservice), params: { ourservice: new_attributes }
        ourservice.reload
        expect(response).to redirect_to(ourservice_url(ourservice))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ourservice = Ourservice.create! valid_attributes
        patch ourservice_url(ourservice), params: { ourservice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ourservice" do
      ourservice = Ourservice.create! valid_attributes
      expect {
        delete ourservice_url(ourservice)
      }.to change(Ourservice, :count).by(-1)
    end

    it "redirects to the ourservices list" do
      ourservice = Ourservice.create! valid_attributes
      delete ourservice_url(ourservice)
      expect(response).to redirect_to(ourservices_url)
    end
  end
end
